### ISSUE TITLE
Broken vines in Biomes O' Plenty biomes with Jurassicraft

### ISSUE THREAD

**Issue by OrcusCZ** [JurassiCraftTeam/JurassiCraft2#532]
When using Biomes O' Plenty (BOP) together with Jurassicraft, there are random purple blocks appearing in all BOP biomes, which should contain vines on trees. For example Tropical Rainforest, Temperate Rainforest, Lush Swamp and so on. All extended vanilla biomes work fine, like Jungle or Swampland.

I have no liteloader, **this is not a liteloader issue.**

When loading affected biome chunks, everything looks fine at first, except there are no vines on the trees. After a few seconds, purple blocks start popping all over the place. I've found out that those blocks behave exactly as vines growing, but for some reason, they are not vines. F3 shows that they are "minecraft:air" , but they have facing information, as a vine should have. I can't pick them up with middle mouse click in creative and I can destroy them by hitting them. Also, their hitbox is the same as vine hitbox.

MCEdit shows that there are some blocks where vines should be, but they have ID 4095 for some reason, although such ID should not be used at all. My guess is that for some reason, BOP generates these blocks instead of correct vine blocks and vine growing algorithm assumes they are air, because their ID is invalid.

I don't know if the problem comes from Jurassicraft or BOP, I've looked at both source codes and can't see anything wrong, but I am not a modder and I am sure I missed something. I am reporting it here, because Jurassicraft overrides minecraft:vine and maybe it breaks something.

I've tested:
- latest version of **Jurassicraft 1.12.2-2.1.20**
- both latest Release version of **BOP 1.12.2-7.0.1.2419** and latest Beta version **BOP 1.12.2-7.0.1.2425**
- latest **Forge 1.12.2 - 14.23.5.2808** and oldest **Forge** supported by LLibrary, which is **1.12.2 - 14.23.5.2772**

The issue is present in all tested versions.

Here is the [debug.log](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2800455/debug.log) and screenshots of such blocks and MCEdit screenshot with block information:

![2019-01-27_19 28 54](https://user-images.githubusercontent.com/12608598/51805731-2e015980-2271-11e9-9189-bace28840058.png)
![2019-01-27_19 29 24](https://user-images.githubusercontent.com/12608598/51805739-35286780-2271-11e9-9045-1a870c637d15.png)
![mcedit](https://user-images.githubusercontent.com/12608598/51805740-3a85b200-2271-11e9-841a-8e8b268f5043.png)

**Comment by PT400C** [comment]
Thank you very much for that report. Just from the point of your observations, it seems that BOP does the same what LiteLoader does codewise with the vines. We'll look into this problem ASAP.

**Comment by OrcusCZ** [comment]
Thank you for looking into it. Tell me if you need more information.

It's not a game breaking bug, Minecraft replaces those weird blocks with air upon loading affected chunks (tested with MCEdit), so as a workaround to get rid of it, one can just restart the server or walk away to unload chunks.

**Comment by Daihok41** [comment]
Any chance the bug has been fixed yet?

**Comment by PT400C** [comment]
@Daihok41 We're in contact with the BOP devs, but currently there has nothing on their end so we can't fix the bug either.

**Comment by littlej541** [comment]
Is there a reason for registering a new block over the default vines to stop them from being placed on glass blocks added by JurassiCraft? It seems a bit smelly if it's just to get the blocks to behave more like vanilla glass. It still doesn't stop vines from growing down over the glass either.

**Comment by PT400C** [comment]
@littlej541 Yes, it's a hack. But it prevents 1. The vines to be placable on the glass and 2. The vines to grow over the glass / spread onto the glass.

**Comment by PT400C** [comment]
So I will close this here, as it's not much likely that the BOP devs will investigate this issue in cooperation with us.

**Comment by PT400C** [comment]
@littlej541 @Daihok41 @OrcusCZ A potential fix is implemented in JC .22.
